image:
  file: .gitpod.Dockerfile
tasks:
    command: |
      eval $(opam env)
      # Install all dependencies from opam file
      opam install --confirm-level=unsafe-yes ./ --deps-only --with-test || true

      # Build the project
      dune build || true

vscode:
  extensions:
    - ocamllabs.ocaml-platform
